# Numpy

- **An array** is a central data structure of the NumPy library. An array is **a grid of values** that can be indexed in various ways.

## Numpy v.s. Array

Suppose we have two vectors with the dimension of four, `a = [1, 2, 3, 4]` and `b = [1, 2, 3, 4]`. We want to make element-wise exponentiations $a^\prime = [1^2, 2^2, 3^2, 4^2]$, $b^\prime = [1^3, 2^3, 3^3, 4^3]$. Then make element-wise addition of $a^\prime$ and $b^\prime$, i.e.,$c = [1^2 + 1^3,  2^2 + 2^3, 3^2 + 3^3, 4^2 + 4^3]$

In [1]:
# use list
a = list(range(1,4))
b = list(range(1,4))

c = []
for index in range(3):
    a[index] = a[index]**2
    b[index] = b[index]**3
    c.append(a[index] + b[index])

print(c)

[2, 12, 36]


In [2]:
# use numpy array
import numpy as np

# Just like created the list using range(), we can creat the numpy arrays using np.arange() 
a = np.array(np.arange(1, 4)) 
b = np.array(np.arange(1, 4))

c = a**2 + b**3 # only use 1-line code, since numpy array supports element-wise calculation

print(c)

[ 2 12 36]


## Create multidimensional arrays

<img src='numpy_arrays.png'>

### `np.array()`

In [3]:
# Dimensions in Arrays
a = np.array(24)

print("Array with zero dimension:", a) #0D array
print("Dimension of the array a: ", a.ndim)
print('shape of array a: ', np.shape(a))
# print('shape of array a: ', a.shape)

Array with zero dimension: 24
Dimension of the array a:  0
shape of array a:  ()


In [4]:
b = np.array([15,20,35,67,89,50])

print("Array with one dimension:",b) #1D array
print("Dimension of the array b: ", b.ndim)
print('shape of array b: ', np.shape(b))
# print('shape of array b: ', b.shape)

Array with one dimension: [15 20 35 67 89 50]
Dimension of the array b:  1
shape of array b:  (6,)


In [5]:
b[5]

50

In [6]:
c = np.array([[10, 20, 30], [40, 50, 60]])
# c_1 = [10, 20, 30]
# c_2 = [40, 50, 60]
# c = np.array([c_1, c_2])

print("Array with two dimension:\n", c) #2D array
print("Dimension of the array c: ", c.ndim)
print('shape of array: ', np.shape(c))

Array with two dimension:
 [[10 20 30]
 [40 50 60]]
Dimension of the array c:  2
shape of array:  (2, 3)


In [7]:
c[1, 2]

60

In [8]:
d = np.array([[[11, 22, 33], [44, 55, 86]], [[61, 28, 38], [47, 85, 65]]])

print("Array with three dimension:\n",d) #3D array
print("Dimension of the array d: ", d.ndim)
print('shape of array', np.shape(d))

Array with three dimension:
 [[[11 22 33]
  [44 55 86]]

 [[61 28 38]
  [47 85 65]]]
Dimension of the array d:  3
shape of array (2, 2, 3)


### `np.arrange()`

In [9]:
# 1D Array

x = np.arange(2,6).reshape(4)
print(x)

[2 3 4 5]


In [10]:
# 2D Array

x = np.arange(2,8).reshape(2,3)
print(x)

[[2 3 4]
 [5 6 7]]


In [11]:
# 3D Array

x = np.arange(24).reshape(4,3,2)
print(x)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


### `np.linespace()`

In [12]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [13]:
np.linspace(2.0, 3.0, num=5, endpoint=False) # By default, endpoint=True, and the end point is included.

array([2. , 2.2, 2.4, 2.6, 2.8])

In [14]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

#### Numpy also provides many functions to create arrays:

In [15]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [16]:
b = np.ones((2,2))
print(b)

[[1. 1.]
 [1. 1.]]


In [17]:
c = np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [18]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [19]:
e = np.random.random((2,2)) # Create an array filled with random values in the half-open interval [0.0, 1.0). 
print(e)

[[0.88310782 0.02072171]
 [0.18781264 0.88694829]]


## Slicing
* Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice indexing for each dimension of the array.

In [20]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [21]:
# A slice of an array is a view into the same data, so modifying it will modify the original array.
A = np.array([10,20,30,40,50,60,70,80,90,10])
A[1:7] = 100
print(A)

[ 10 100 100 100 100 100 100  80  90  10]


* You can also mix **integer indexing** with **slice indexing**. However, doing so will yield an array of lower rank than the original array. 
* Using only slices yields an array of the same rank as the original array.

In [22]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [23]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [24]:
d = np.array([[[11, 22, 33], [44, 55, 86]], [[61, 28, 38], [47, 85, 65]]])
d[0:2,1:,1:] # slicing a 3-D array

array([[[55, 86]],

       [[85, 65]]])

In [25]:
d[0, 1, 1] # Integer Indexing, taking a specified element

55

In [26]:
e = d[0, :, :]
print(e)
# print(d.shape, e.shape)

[[11 22 33]
 [44 55 86]]


In [27]:
f = d[0:1, :, :]
print(f)
# print(d.shape, f.shape)

[[[11 22 33]
  [44 55 86]]]


In [28]:
# Slicing using Step
t = np.array([81, 24, 36, 42, 5, 96, 7])
print("Slicing with step size 2:", t[1:5:2])

Slicing with step size 2: [24 42]


In [29]:
# Negative Slicing
a = np.array([9, 23, 63, 4, 56, 86, 97])
print("Negative Slicing:",a[-3:-1])

Negative Slicing: [56 86]


Boolean array indexing: 
* Boolean array indexing lets you pick out arbitrary elements of an array. This type of indexing is often used to select the elements of an array that satisfy some condition. Here is an example:

In [30]:
A = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# We are filtering element using greater than 50
bool_idx = (A>50)   # Find the elements of a that are bigger than 50;
                    # this returns a numpy array of Booleans of the same
                    # shape as A, where each slot of bool_idx tells
                    # whether that element of A is > 50.
print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(A[bool_idx])


[False False False False False  True  True  True  True  True]
[ 60  70  80  90 100]


In [31]:
# We can do all of the above in a single concise statement:
A = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(A[A>50])

[ 60  70  80  90 100]


In [32]:
A = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(A[A%30==0])

[30 60 90]


## Data types

Every numpy array is a grid of elements of the **same type**. Numpy provides a large set of numeric datatypes that you can use to construct arrays. You can read all about numpy datatypes in the [documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [33]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype) # Checking the Data Type 

int64 float64 int64


In [34]:
A = np.array([[10, 20.],[30, 40],[50, 60]], dtype='str') 
print(A)
print(A.dtype) # 4-character string

[['10' '20.0']
 ['30' '40']
 ['50' '60']]
<U4


## Iterable

In [35]:
x = np.array([81, 12, 30, 56, 78])
print("Iteration of 1D array:")
for a in x:
    print(a)

Iteration of 1D array:
81
12
30
56
78


In [36]:
# Iteratin 2D arrays
y = np.array([[13, 42, 37], [46, 58, 69]])
print("Iteration of 2D array:")
for b in y:
    print(b)

Iteration of 2D array:
[13 42 37]
[46 58 69]


In [37]:
# Iteration of 3D arrays
z = np.array([[[61, 82, 30], [40, 5, 46]], [[87, 80, 94], [150, 151, 162]]])
print("Iteration of 3D array:")
for c in z:
    print(c)

Iteration of 3D array:
[[61 82 30]
 [40  5 46]]
[[ 87  80  94]
 [150 151 162]]


## Array Math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [38]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [39]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [40]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [41]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [42]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [43]:
print(np.power(x, 4))

[[  1.  16.]
 [ 81. 256.]]


In [44]:
print(np.negative(np.array([1, 2, 3])))

[-1 -2 -3]


In [45]:
print(np.log(x))
# np.info(np.log)

[[0.         0.69314718]
 [1.09861229 1.38629436]]


In [46]:
print(np.sin(x))

[[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]


* Note that `*` is elementwise multiplication, not matrix multiplication. 
* We use the **dot function** to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. 
* dot is available both as a function in the numpy module and as an instance method of array objects:

In [47]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


* You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [48]:
print(v @ w)

219


In [49]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [50]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [51]:
import numpy as np
# We are finding sum of rows, columns
A = np.array([[1, 2],[3, 4],[5, 6]]) 
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
print(np.sum(A))  # Compute sum of all elements;

21


In [53]:
sumrow = A.sum(axis=1) # sumrow = A.sum(-1) 
print("sum of rows is: ", sumrow) # Compute sum of each row

sumcol = A.sum(axis=0)
print("sum of columns is: ", sumcol) # Compute sum of each column

sum of rows is:  [ 3  7 11]
sum of columns is:  [ 9 12]


In [54]:
# Qs? 
print(A[sumrow%3==0])

[[1 2]]


You can find the **full list of mathematical functions provided by numpy** in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the `T` attribute of an array object:

In [55]:
x = np.array([[1,2],[3,4]])
print(x)

print("transpose\n", x.T) # transpose a matrix
print("transpose\n", np.transpose(x)) # transpose a matrix

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]
transpose
 [[1 3]
 [2 4]]


In [56]:
# We use numpy.linalg.inv() function to calculate the inverse of a matrix. 
print("inverse\n", np.linalg.inv(x))

inverse
 [[-2.   1. ]
 [ 1.5 -0.5]]


## Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. 

* We have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array. For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [57]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [58]:
# The above broad casting is equivalent to adding the vector v to each row of the matrix x
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [59]:
# Adding the vector v to each row of the matrix x is equivalent 
# to forming a matrix vv by stacking multiple copies of v vertically, 
# then performing elementwise summation of x and vv. 
# We could implement this approach like this:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"      
y = x + vv  # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


* In summary: Numpy broadcasting allows us to perform this computation without actually creating multiple copies of `v`.

* **Broadcasting two arrays together follows certain rules.** Try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html).

* Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [60]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

[[2 2 4]
 [5 5 7]]


In [61]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [62]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [63]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [64]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


* Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

## Other useful functions

In [65]:
a = np.array([0, 1, 1, 2, 3, 4, 1])
x = np.where(a == 1) #Searching of an element in the array and returing the index.
print(x)

(array([1, 2, 6]),)


In [66]:
#Filter function: Getting some elements out of an existing array and creating a new array out of them
#Syntax: var3=var1[var2]

p = np.array([10, 20, 30, 40, 50, 60, 70])
q = [True, False, True, False, True, True, False]
r = p[q]
print(r)

[10 30 50 60]


In [67]:
a = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
b = np.unique(a) #Discarding the repeated elements in an array
print(b)

[1 2 3 4 5 6 7]


In [68]:
a = np.array(['monkey', 'cat', 'elephant', 'mouse', 'zebra', 'dog']) 
print(np.sort(a)) #Sorting of elements of an array.

['cat' 'dog' 'elephant' 'monkey' 'mouse' 'zebra']


In [69]:
# We are sorting with first axis
A = np.array([[24, 48], [67, 56]])
A1 = np.sort(A, axis = 1)
print(A1)

[[24 48]
 [56 67]]


In [70]:
# We are sorting with last axis
A = np.array([[8, 42], [54, 28]])
A2 = np.sort(A, axis = -1)
print (A2)

[[ 8 42]
 [28 54]]


In [71]:
# We are sorting without any axis
A = np.array([[42, 28], [99, 56]])
A1 = np.sort(A, axis = None)
print (A1)

[28 42 56 99]


In [72]:
# We are counting a number of non-zero values
A = np.count_nonzero([[24,0,0,28,0],[0,38,0,0,56]])
print(A)

4


This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.